name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Our tests are not thread-safe due to environment variable manipulation.
  RUST_TEST_THREADS: 1

jobs:
  # Only run first-party OIDC tests on events that don't come from forks,
  # since forks can't access the workflow's OIDC identity.
  test-1p:
    name: First-party OIDC tests
    if: (github.event_name != 'pull_request') || !github.event.pull_request.head.repo.fork
    permissions:
      id-token: write # needed for first-party OIDC tests
      contents: read # for private repos

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2

      - name: Run tests
        run: cargo test --features test-github-1p

  test-3p:
    name: Third-party OIDC tests
    permissions:
      contents: read # for private repos

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2

      - name: Run tests
        run: cargo test
